### ISSUE TITLE
test Help

### ISSUE THREAD

**Issue by Yu-Wang-0801** [LongguangWang/PASSRnet#2]
Hello, how do you test with your own trained model? The model file you regenerate is in .tar format, for example: PassRnet_x4_epoch80.pth.tar. Is it necessary to change the model generated by myself to the model folder with the same name of the existing model file PASSRnet_x4.pth, and then test it?
Another problem is that you can only test a single test. When you put all the tests into the same dataset, can you test them at the same time?

**Comment by dannilv-lab** [comment]
> Hello, how do you test with your own trained model? The model file you regenerate is in .tar format, for example: PassRnet_x4_epoch80.pth.tar. Is it necessary to change the model generated by myself to the model folder with the same name of the existing model file PASSRnet_x4.pth, and then test it?
> Another problem is that you can only test a single test. When you put all the tests into the same dataset, can you test them at the same time?
Have you solved your problem? How exactly did it work out? I had the same problem。

**Comment by dannilv-lab** [comment]
Have you solved your problem? How exactly did it work out? I had the same problem。

**Comment by chenjiachengzzz** [comment]
> Hello, how do you test with your own trained model? The model file you regenerate is in .tar format, for example: PassRnet_x4_epoch80.pth.tar. Is it necessary to change the model generated by myself to the model folder with the same name of the existing model file PASSRnet_x4.pth, and then test it? Another problem is that you can only test a single test. When you put all the tests into the same dataset, can you test them at the same time?

Have you solved your problem? How exactly did it work out? I had the same problem。

**Comment by chenjiachengzzz** [comment]
> Have you solved your problem? How exactly did it work out? I had the same problem。

Have you solved your problem?
