### ISSUE TITLE
Middlebury  数据集问题

### ISSUE THREAD

**Issue by clttyou** [LongguangWang/PASSRnet#8]

**Comment by clttyou** [comment]
在论文中 For test, we used 5 images from the Middlebury dataset,但是我发现在 Middlebury 数据集（https://vision.middlebury.edu/stereo/data/）下的每类图像下都包含多个文件夹，请问该实验具体是用了那几张Middlebury数据来测试（我已按照数据集的要求进行挑选图像测试，但得到的psnr=36和文中的 28.63相差较大）？谢谢

**Comment by misaka0326** [comment]
> 在论文中 For test, we used 5 images from the Middlebury dataset,但是我发现在 Middlebury 数据集（[https://vision.middlebury.edu/stereo/data/）下的每类图像下都包含多个文件夹，请问该实验具体是用了那几张Middlebury数据来测试（我已按照数据集的要求进行挑选图像测试，但得到的psnr=36和文中的](https://vision.middlebury.edu/stereo/data/%EF%BC%89%E4%B8%8B%E7%9A%84%E6%AF%8F%E7%B1%BB%E5%9B%BE%E5%83%8F%E4%B8%8B%E9%83%BD%E5%8C%85%E5%90%AB%E5%A4%9A%E4%B8%AA%E6%96%87%E4%BB%B6%E5%A4%B9%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%AF%A5%E5%AE%9E%E9%AA%8C%E5%85%B7%E4%BD%93%E6%98%AF%E7%94%A8%E4%BA%86%E9%82%A3%E5%87%A0%E5%BC%A0Middlebury%E6%95%B0%E6%8D%AE%E6%9D%A5%E6%B5%8B%E8%AF%95%EF%BC%88%E6%88%91%E5%B7%B2%E6%8C%89%E7%85%A7%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E8%A6%81%E6%B1%82%E8%BF%9B%E8%A1%8C%E6%8C%91%E9%80%89%E5%9B%BE%E5%83%8F%E6%B5%8B%E8%AF%95%EF%BC%8C%E4%BD%86%E5%BE%97%E5%88%B0%E7%9A%84psnr=36%E5%92%8C%E6%96%87%E4%B8%AD%E7%9A%84) 28.63相差较大）？谢谢

我测试的Middlebury数据集也是这样……4X上采样在RGB三通道上的PSNR值是32.70，y通道是34.47，困惑，摸不着头脑

**Comment by clttyou** [comment]
> > 在论文中 For test, we used 5 images from the Middlebury dataset,但是我发现在 Middlebury 数据集（[https://vision.middlebury.edu/stereo/data/）下的每类图像下都包含多个文件夹，请问该实验具体是用了那几张Middlebury数据来测试（我已按照数据集的要求进行挑选图像测试，但得到的psnr=36和文中的](https://vision.middlebury.edu/stereo/data/%EF%BC%89%E4%B8%8B%E7%9A%84%E6%AF%8F%E7%B1%BB%E5%9B%BE%E5%83%8F%E4%B8%8B%E9%83%BD%E5%8C%85%E5%90%AB%E5%A4%9A%E4%B8%AA%E6%96%87%E4%BB%B6%E5%A4%B9%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%AF%A5%E5%AE%9E%E9%AA%8C%E5%85%B7%E4%BD%93%E6%98%AF%E7%94%A8%E4%BA%86%E9%82%A3%E5%87%A0%E5%BC%A0Middlebury%E6%95%B0%E6%8D%AE%E6%9D%A5%E6%B5%8B%E8%AF%95%EF%BC%88%E6%88%91%E5%B7%B2%E6%8C%89%E7%85%A7%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E8%A6%81%E6%B1%82%E8%BF%9B%E8%A1%8C%E6%8C%91%E9%80%89%E5%9B%BE%E5%83%8F%E6%B5%8B%E8%AF%95%EF%BC%8C%E4%BD%86%E5%BE%97%E5%88%B0%E7%9A%84psnr=36%E5%92%8C%E6%96%87%E4%B8%AD%E7%9A%84) 28.63相差较大）？谢谢
> 
> 我测试的Middlebury数据集也是这样……4X上采样在RGB三通道上的PSNR值是32.70，y通道是34.47，困惑，摸不着头脑

已发至你邮箱

**Comment by misaka0326** [comment]
> > > 在论文中 For test, we used 5 images from the Middlebury dataset,但是我发现在 Middlebury 数据集（[https://vision.middlebury.edu/stereo/data/）下的每类图像下都包含多个文件夹，请问该实验具体是用了那几张Middlebury数据来测试（我已按照数据集的要求进行挑选图像测试，但得到的psnr=36和文中的](https://vision.middlebury.edu/stereo/data/%EF%BC%89%E4%B8%8B%E7%9A%84%E6%AF%8F%E7%B1%BB%E5%9B%BE%E5%83%8F%E4%B8%8B%E9%83%BD%E5%8C%85%E5%90%AB%E5%A4%9A%E4%B8%AA%E6%96%87%E4%BB%B6%E5%A4%B9%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%AF%A5%E5%AE%9E%E9%AA%8C%E5%85%B7%E4%BD%93%E6%98%AF%E7%94%A8%E4%BA%86%E9%82%A3%E5%87%A0%E5%BC%A0Middlebury%E6%95%B0%E6%8D%AE%E6%9D%A5%E6%B5%8B%E8%AF%95%EF%BC%88%E6%88%91%E5%B7%B2%E6%8C%89%E7%85%A7%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E8%A6%81%E6%B1%82%E8%BF%9B%E8%A1%8C%E6%8C%91%E9%80%89%E5%9B%BE%E5%83%8F%E6%B5%8B%E8%AF%95%EF%BC%8C%E4%BD%86%E5%BE%97%E5%88%B0%E7%9A%84psnr=36%E5%92%8C%E6%96%87%E4%B8%AD%E7%9A%84) 28.63相差较大）？谢谢
> > 
> > 
> > 我测试的Middlebury数据集也是这样……4X上采样在RGB三通道上的PSNR值是32.70，y通道是34.47，困惑，摸不着头脑
> 
> 已发至你邮箱

嗯？什么邮箱？没有收到啊，我的邮箱是tmli@stu.xidian.edu.cn，麻烦你重新发一下啦

**Comment by clttyou** [comment]
> tmli@stu.xidian.edu.cn
你好，你提供的邮箱无法发送。
链接：https://pan.baidu.com/s/1nMwY0EBAgh_pAjrUpevbbg 
提取码：v2bp 
复制这段内容后打开百度网盘手机App，操作更方便哦
可以直接下载Middlebury测试数据集

**Comment by clttyou** [comment]
> > > > 在论文中 For test, we used 5 images from the Middlebury dataset,但是我发现在 Middlebury 数据集（[https://vision.middlebury.edu/stereo/data/）下的每类图像下都包含多个文件夹，请问该实验具体是用了那几张Middlebury数据来测试（我已按照数据集的要求进行挑选图像测试，但得到的psnr=36和文中的](https://vision.middlebury.edu/stereo/data/%EF%BC%89%E4%B8%8B%E7%9A%84%E6%AF%8F%E7%B1%BB%E5%9B%BE%E5%83%8F%E4%B8%8B%E9%83%BD%E5%8C%85%E5%90%AB%E5%A4%9A%E4%B8%AA%E6%96%87%E4%BB%B6%E5%A4%B9%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%AF%A5%E5%AE%9E%E9%AA%8C%E5%85%B7%E4%BD%93%E6%98%AF%E7%94%A8%E4%BA%86%E9%82%A3%E5%87%A0%E5%BC%A0Middlebury%E6%95%B0%E6%8D%AE%E6%9D%A5%E6%B5%8B%E8%AF%95%EF%BC%88%E6%88%91%E5%B7%B2%E6%8C%89%E7%85%A7%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E8%A6%81%E6%B1%82%E8%BF%9B%E8%A1%8C%E6%8C%91%E9%80%89%E5%9B%BE%E5%83%8F%E6%B5%8B%E8%AF%95%EF%BC%8C%E4%BD%86%E5%BE%97%E5%88%B0%E7%9A%84psnr=36%E5%92%8C%E6%96%87%E4%B8%AD%E7%9A%84) 28.63相差较大）？谢谢
> > > 
> > > 
> > > 我测试的Middlebury数据集也是这样……4X上采样在RGB三通道上的PSNR值是32.70，y通道是34.47，困惑，摸不着头脑
> > 
> > 
> > 已发至你邮箱
> 
> 嗯？什么邮箱？没有收到啊，我的邮箱是[tmli@stu.xidian.edu.cn](mailto:tmli@stu.xidian.edu.cn)，麻烦你重新发一下啦

**Comment by clttyou** [comment]
> > > > 在论文中 For test, we used 5 images from the Middlebury dataset,但是我发现在 Middlebury 数据集（[https://vision.middlebury.edu/stereo/data/）下的每类图像下都包含多个文件夹，请问该实验具体是用了那几张Middlebury数据来测试（我已按照数据集的要求进行挑选图像测试，但得到的psnr=36和文中的](https://vision.middlebury.edu/stereo/data/%EF%BC%89%E4%B8%8B%E7%9A%84%E6%AF%8F%E7%B1%BB%E5%9B%BE%E5%83%8F%E4%B8%8B%E9%83%BD%E5%8C%85%E5%90%AB%E5%A4%9A%E4%B8%AA%E6%96%87%E4%BB%B6%E5%A4%B9%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%AF%A5%E5%AE%9E%E9%AA%8C%E5%85%B7%E4%BD%93%E6%98%AF%E7%94%A8%E4%BA%86%E9%82%A3%E5%87%A0%E5%BC%A0Middlebury%E6%95%B0%E6%8D%AE%E6%9D%A5%E6%B5%8B%E8%AF%95%EF%BC%88%E6%88%91%E5%B7%B2%E6%8C%89%E7%85%A7%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E8%A6%81%E6%B1%82%E8%BF%9B%E8%A1%8C%E6%8C%91%E9%80%89%E5%9B%BE%E5%83%8F%E6%B5%8B%E8%AF%95%EF%BC%8C%E4%BD%86%E5%BE%97%E5%88%B0%E7%9A%84psnr=36%E5%92%8C%E6%96%87%E4%B8%AD%E7%9A%84) 28.63相差较大）？谢谢
> > > 
> > > 
> > > 我测试的Middlebury数据集也是这样……4X上采样在RGB三通道上的PSNR值是32.70，y通道是34.47，困惑，摸不着头脑
> > 
> > 
> > 已发至你邮箱
> 
> 嗯？什么邮箱？没有收到啊，我的邮箱是[tmli@stu.xidian.edu.cn](mailto:tmli@stu.xidian.edu.cn)，麻烦你重新发一下啦

你好，你提供的邮箱无法发送。
链接：https://pan.baidu.com/s/1nMwY0EBAgh_pAjrUpevbbg 
提取码：v2bp 
复制这段内容后打开百度网盘手机App，操作更方便哦
可以直接下载Middlebury测试数据集

**Comment by misaka0326** [comment]
> > > > > 在论文中 For test, we used 5 images from the Middlebury dataset,但是我发现在 Middlebury 数据集（[https://vision.middlebury.edu/stereo/data/）下的每类图像下都包含多个文件夹，请问该实验具体是用了那几张Middlebury数据来测试（我已按照数据集的要求进行挑选图像测试，但得到的psnr=36和文中的](https://vision.middlebury.edu/stereo/data/%EF%BC%89%E4%B8%8B%E7%9A%84%E6%AF%8F%E7%B1%BB%E5%9B%BE%E5%83%8F%E4%B8%8B%E9%83%BD%E5%8C%85%E5%90%AB%E5%A4%9A%E4%B8%AA%E6%96%87%E4%BB%B6%E5%A4%B9%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%AF%A5%E5%AE%9E%E9%AA%8C%E5%85%B7%E4%BD%93%E6%98%AF%E7%94%A8%E4%BA%86%E9%82%A3%E5%87%A0%E5%BC%A0Middlebury%E6%95%B0%E6%8D%AE%E6%9D%A5%E6%B5%8B%E8%AF%95%EF%BC%88%E6%88%91%E5%B7%B2%E6%8C%89%E7%85%A7%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E8%A6%81%E6%B1%82%E8%BF%9B%E8%A1%8C%E6%8C%91%E9%80%89%E5%9B%BE%E5%83%8F%E6%B5%8B%E8%AF%95%EF%BC%8C%E4%BD%86%E5%BE%97%E5%88%B0%E7%9A%84psnr=36%E5%92%8C%E6%96%87%E4%B8%AD%E7%9A%84) 28.63相差较大）？谢谢
> > > > 
> > > > 
> > > > 我测试的Middlebury数据集也是这样……4X上采样在RGB三通道上的PSNR值是32.70，y通道是34.47，困惑，摸不着头脑
> > > 
> > > 
> > > 已发至你邮箱
> > 
> > 
> > 嗯？什么邮箱？没有收到啊，我的邮箱是[tmli@stu.xidian.edu.cn](mailto:tmli@stu.xidian.edu.cn)，麻烦你重新发一下啦
> 
> 你好，你提供的邮箱无法发送。
> 链接：https://pan.baidu.com/s/1nMwY0EBAgh_pAjrUpevbbg
> 提取码：v2bp
> 复制这段内容后打开百度网盘手机App，操作更方便哦
> 可以直接下载Middlebury测试数据集

已下载，谢谢~
